#!/bin/bash
d=0
while true ; do
    [ -e "/tmp/.X$d-lock" -o -S "/tmp/.X11-unix/X$d" ] || break
    d=$(($d + 1))
done
export DISPLAY=":$d"
unset d

export I3SWAY_SESSION=i3
geni3config
exec xinit /bin/bash -c 'xrdb -merge ~/.config/i3/Xresources; exec i3 -c /run/user/$UID/i3.conf' -- $DISPLAY vt$XDG_VTNR -nolisten tcp
